# Generated by Django 5.0.1 on 2024-02-01 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_book_cover_book_description_book_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateField(default=datetime.datetime(2024, 2, 1, 9, 10, 34, 520334, tzinfo=datetime.timezone.utc)),
        ),
    ]
